### ISSUE TITLE
need help: "Unsupported parameter: javax.crypto.spec.IvParameterSpec"

### ISSUE THREAD

**Issue by ourcodeslist** [ben221199/WAPI#9]
I got the following error
`
java.security.InvalidAlgorithmParameterException: Unsupported parameter: javax.crypto.spec.IvParameterSpec@4667ae56
	at java.base/com.sun.crypto.provider.CipherCore.init(CipherCore.java:520)
	at java.base/com.sun.crypto.provider.AESCipher.engineInit(AESCipher.java:346)
	at java.base/javax.crypto.Cipher.implInit(Cipher.java:871)
	at java.base/javax.crypto.Cipher.chooseProvider(Cipher.java:929)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1444)
	at java.base/javax.crypto.Cipher.init(Cipher.java:1375)
	at nl.ben221199.wapi.Verification.encryptParameters(Verification.java:175)
`

**Comment by ben221199** [comment]
Did you add the following code?
```Java
static{
	Security.addProvider(new BouncyCastleProvider());
}
```

The `Verification` class depends on a algorithm that isn't supported by the basic Java framework, but is added by the BouncyCastle library. In order to get support for this algorithm, you have to add the `BouncyCastleProvider` as provider.

**Comment by ourcodeslist** [comment]
Works

**Comment by ourcodeslist** [comment]
Works. thx
